### ISSUE TITLE
User Story 14: Use of AI

### ISSUE THREAD

**Issue by Asad-1I** [Asad-1I/JS-Quiz#3]
User Story 14: Use of AI

**User Story 14: Use of AI:**
As a user of the site I expect modern tools to be used in the creation and development of the site so that I get user best user experience.

**Acceptance Criteria:**
- [ ] AI is used to assist with coding
- [ ] AI is used to assist with validation and debugging
- [ ] AI may be used to assist with image generation

**Tasks:**
- [ ] Use Copilot in VS Code
- [ ] Optional: Use AI image generators.
