### ISSUE TITLE
User Story 15: Documentation

### ISSUE THREAD

**Issue by Asad-1I** [Asad-1I/JS-Quiz#4]
User Story 15: Documentation
**User Story 15: Documentation:**
As a fellow coder I would like to see the development documentation and marked up comments on the code so that I can get a better insight into the process and understanding of the code.

**Acceptance Criteria:**
- [ ] A ReadMe document should be attached to the project and embedded in the repository
- [ ] The ReadMe should be logically laid out for ease of reading
- [ ] Comments should be used across all pages of the code (i.e. HTML, CSS and JS)

**Tasks:**
- [ ] Create ReadMe
- [ ] Use appropriate sections and headings as well as hyperlinks where possible to ease navigation
- [ ] Ensure comments are added to the code frequently
