### ISSUE TITLE
User Story 8: Responsiveness

### ISSUE THREAD

**Issue by Asad-1I** [Asad-1I/JS-Quiz#8]
User Story 8: Responsiveness

**User Story 8: Responsiveness:**
As a user who has multiple devices I want the site to look as good as possible on a variety of different screen sizes, preferably on a single screen on each, so that I can have the best user experience.

**Acceptance Criteria:**
- [ ] The site should look good on mobile, tablet and laptop/desktop.
- [ ] The site should be on a single screen.

**Tasks:**
- [ ] Use media queries to achieve the best responsive appearance on all device types.
- [ ] Check appearance using different device types
- [ ] Keep code concise to ensure appears on single screen and use comments.
